# .gitlab-ci.yml
image: alpine:latest

pages:
  publish: "."               # Serve everything from the root
  rules:
    - if: $CI_COMMIT_REF_NAME == "dev"
  script:
    - echo "Deploying from dev branch to GitLab Pages"