image: alpine:latest

create-pages:
  stage: deploy
  script:
    - echo "Deploying Pages"
  artifacts:
    paths:
      - dev
  pages:
    publish: dev
  rules:
    - if: $CI_COMMIT_REF_NAME == $CI_DEFAULT_BRANCH